api/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, division, print_function

from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'panoramas', views.PanoramaViewSet)
router.register(r'refpoints', views.ReferencePointViewSet)
router.register(r'references', views.ReferenceViewSet)

urlpatterns = [
    path('', include(router.urls)),
#    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

celutz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('altitude/', include('altitude.urls', namespace="altitude")),
    path('', include('panorama.urls', namespace="panorama")),
    path('api/v1/', include('api.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
# In debug mode, serve tiles
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panorama/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import path, re_path

from .views import MainView, PanoramaUpload, PanoramaView, PanoramaGenTiles, LocateReferencePointView, LocateCustomPointView, CreateReferencePoint

app_name = 'panorama'
urlpatterns = [
    re_path(r'^$', MainView.as_view(), name="main"),
    path('locate_refpoint/', LocateReferencePointView.as_view(), name="locate_refpoint"),
    path('locate_custompoint/', LocateCustomPointView.as_view(), name="locate_custompoint"),
    path('pano/new/', PanoramaUpload.as_view(), name="new"),
    path('refpoint/new/', CreateReferencePoint.as_view(), name="new_refpoint"),
    path('pano/view/<int:pk>/', PanoramaView.as_view(), name="view_pano"),
    path('pano/gen_tiles/<int:pk>/', PanoramaGenTiles.as_view(), name="gen_tiles"),
]

panorama/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.utils.translation import gettext_lazy as _

from .models import ReferencePoint, Panorama


class SelectReferencePointForm(forms.Form):
    """Form to select an existing reference point"""
    q = ReferencePoint.objects.order_by("name")
    reference_point = forms.ModelChoiceField(queryset=q,label=_("Reference point"))


class CustomPointForm(forms.ModelForm):
    """Form to use a custom point as input."""
    prefix = 'custompoint'

    class Meta:
        model = ReferencePoint
        fields = ['latitude', 'longitude', 'ground_altitude', 'height_above_ground']

class PanoramaForm(forms.ModelForm):
    """Form to insert a new panorama."""
    prefix = 'newpano'

    class Meta:
        model = Panorama
        fields = ['name', 'image', 'loop', 'latitude', 'longitude', 'ground_altitude', 'height_above_ground']

class ReferencePointForm(forms.ModelForm):
    """Form to insert a new reference point"""
    prefix = 'newrefpoint'

    class Meta:
        model = ReferencePoint
        fields = ['name', 'latitude', 'longitude', 'ground_altitude', 'height_above_ground', 'kind']

panorama/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, RedirectView, ListView, TemplateView
from django.views.decorators.csrf import ensure_csrf_cookie
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Point, Panorama, ReferencePoint
from .forms import SelectReferencePointForm, CustomPointForm, PanoramaForm, ReferencePointForm


class CelutzLoginMixin(LoginRequiredMixin):
    """Mixin that acts like LoginRequiredMixin if settings.LOGIN_REQUIRED is
    True, and does nothing otherwise.  It allows to choose whether
    accessing celutz requires an account or is open to anybody.
    """
    login_url = '/admin/login/'

    def dispatch(self, request, *args, **kwargs):
        """Small hack: either call our parent (LoginRequiredMixin) or bypass it"""
        if settings.LOGIN_REQUIRED:
            return super(CelutzLoginMixin, self).dispatch(request, *args, **kwargs)
        else:
            return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class PanoramaUpload(CelutzLoginMixin, CreateView):
    model = Panorama
    fields = ('name', 'image', 'loop', 'latitude', 'longitude', 'ground_altitude', 'height_above_ground')
    template_name = "panorama/new.html"
    prefix = 'newpano'

    def get_success_url(self):
        return reverse_lazy("panorama:gen_tiles", kwargs={"pk": self.object.id})


@method_decorator(ensure_csrf_cookie, name='dispatch')
class PanoramaView(CelutzLoginMixin, DetailView):
    model = Panorama
    template_name = "panorama/view.html"
    context_object_name = "panorama"

    def get_context_data(self, **kwargs):
        context = super(PanoramaView, self).get_context_data(**kwargs)
        pano = context['panorama']
        context['panoramas'] = [p for p in Panorama.objects.all() if pano.great_circle_distance(p) <= settings.PANORAMA_MAX_DISTANCE]
        context['poi_list'] = [poi for poi in ReferencePoint.objects.all() if not hasattr(poi, 'panorama') and pano.great_circle_distance(poi) <= settings.PANORAMA_MAX_DISTANCE]
        return context



class PanoramaGenTiles(CelutzLoginMixin, RedirectView):
    permanent = False
    pattern_name = "panorama:view_pano"

    def get_redirect_url(self, *args, **kwargs):
        pano = get_object_or_404(Panorama, pk=kwargs['pk'])
        pano.generate_tiles()
        return super(PanoramaGenTiles, self).get_redirect_url(*args, **kwargs)


class MainView(CelutzLoginMixin, TemplateView):
    template_name = "panorama/main.html"

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        context['refpoints_form'] = SelectReferencePointForm
        context['custom_point_form'] = CustomPointForm
        context['newpanorama_form'] = PanoramaForm
        context['newrefpoint_form'] = ReferencePointForm
        context['panoramas'] = Panorama.objects.all()
        context['poi_list'] = [poi for poi in ReferencePoint.objects.all() if not hasattr(poi, 'panorama')]
        return context

    def compute_interesting_panoramas(self, point):
        """Compute all panoramas that see the given point, along with the distance
        and direction from each panorama towards the point.  Returns a
        list of (panorama, distance, bearing, elevation) triples.
        """
        if isinstance(point, ReferencePoint):
            queryset = Panorama.objects.exclude(id=point.id)
        else:
            queryset = Panorama.objects
        l = [(pano, pano.line_distance(point), pano.bearing(point), pano.elevation(point))
             for pano in queryset.all() if pano.is_visible(point) and pano.great_circle_distance(point) <= settings.LOCATE_POINT_MAX_DISTANCE]
        # Sort by increasing distance
        return sorted(l, key=lambda x: x[1])


class CreateReferencePoint(CelutzLoginMixin, CreateView):
    model = ReferencePoint
    fields = ('name', 'latitude', 'longitude', 'ground_altitude', 'height_above_ground', 'kind')
    template_name = 'panorama/new-refpoint.html'
    prefix = 'newrefpoint'

    def get_success_url(self):
        return reverse_lazy("panorama:main")


class LocateReferencePointView(MainView):
    """Displays a located reference point"""
    template_name = 'panorama/locate_point.html'

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        form = SelectReferencePointForm(request.POST)
        if form.is_valid():
            point = form.cleaned_data['reference_point']
            context['located_panoramas'] = self.compute_interesting_panoramas(point)
            context['located_point_name'] = point.name
            context['located_point_lat'] = point.latitude
            context['located_point_lon'] = point.longitude
        return super(LocateReferencePointView, self).render_to_response(context)


class LocateCustomPointView(MainView):
    """Displays a located custom GPS point"""
    template_name = 'panorama/locate_point.html'

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        form = CustomPointForm(request.POST)
        if form.is_valid():
            point = Point(**form.cleaned_data)
            context['located_panoramas'] = self.compute_interesting_panoramas(point)
            context['located_point_lat'] = point.latitude
            context['located_point_lon'] = point.longitude
        return super(LocateCustomPointView, self).render_to_response(context)

panorama/templates/panorama/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="{{ LANGUAGE_CODE }}" lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8"/>
    <title>{% block title %}{% endblock title %}</title>

    <link type="image/x-icon" rel="shortcut icon" href="{% static "panorama/img/tsf.png" %}"/>

    <link href="{% static "panorama/css/bootstrap.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "panorama/css/sb-admin.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "panorama/css/plugins/morris.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "panorama/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "panorama/css/celutz.css" %}" rel="stylesheet" media="screen">
    <link href="{% static "panorama/css/bootstrap-select/1.11.2/css/bootstrap-select.min.css" %}" rel="stylesheet" type="text/css">
    {% block css %}{% endblock css %}

    <script type='text/javascript' src="{% static "panorama/js/html5shiv/3.7.0/html5shiv.js" %}"></script>
    <script type='text/javascript' src="{% static "panorama/js/respond.js/1.4.2/respond.min.js" %}"></script>
    <script type='text/javascript' src="{% static "panorama/js/jquery-3.1.0.min.js" %}"></script>
    <script type='text/javascript' src="{% static "panorama/js/bootstrap-select/1.11.2/js/bootstrap-select.min.js" %}"></script>
  </head>

  <body>
    {# Add base structure here, menu, etc... #}
   <div id="wrapper" {% block wrapper-style %}{% endblock wrapper-style %}>
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {% block top-menu-title %}
                {% endblock top-menu-title %}
            </div>
            <ul class="nav navbar-pano top-nav">
                {% block top-menu-pano-items %}
                {% endblock top-menu-pano-items %}
            </ul>
            <ul class="nav navbar-right top-nav">
                {% block top-menu-items %}
                {% endblock top-menu-items %}
                <li>
                    <a href="{% url 'admin:index' %}"><i class="fa fa-pencil-square-o"></i>  {% trans "Admin" %}</a>
                </li>
                <li class="dropdown langue">
                  <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}" />
                    <select class="selectpicker" title="     {% trans "Language" %}" name="language" onchange='this.form.submit()'>
                      {% get_available_languages as LANGUAGES %}
                      {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                          <option value="{{ language.code }}">
                               {{ language.name_local }}
                          </option>
                        {% endfor %}
                    </select>
                    <noscript><input type="submit" value="Submit"></noscript>
                  </form>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-info-circle"></i>  {% trans "About" %}<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                           <p>{% blocktrans %}Celutz is a tool for managing and referencing panoramic photos{% endblocktrans %}.
                           <a href="https://code.ffdn.org/FFDN/celutz/">{% trans "Project homepage" %}</a>
                        </li>
                    </ul>
                </li>
            </ul>
            {% block sidebar %}
            {% endblock sidebar %}
        </nav>
        {% block pano %}{% endblock pano %}
        <div id="page-wrapper" {% block page-wrapper-style %}{% endblock page-wrapper-style %}>
        {% block content %}{% endblock content %}
        </div>
    </div>
    {% block js %}
    {% endblock js %}

    <script src="{% static "panorama/js/jquery.js" %}"></script>
    <script src="{% static "panorama/js/bootstrap.min.js" %}"></script>
  </body>
</html>

panorama/templates/panorama/locate_point.html
{% extends "panorama/main.html" %}
{% load panorama_url %}
{% load static %}
{% load distance_filter %}
{% load i18n %}
{% load l10n %}

{% block title %}{% trans "Result of research"%}{% endblock title %}

{% block top-menu-title %}
    <a class="navbar-brand" href="{% url 'panorama:main' %}"><i class="fa fa-fw fa-home"></i></a>

{% endblock %}

{% block top-menu-items %}
{% endblock %}

{% block top-menu-pano-items %}
    {% if located_panoramas|length == 0 %}
        <a class="navbar-brand result-title" href="#">{% trans "No panorama seeing this point !" %}</a>
    {% else %}
        {% if located_point_name != None %}
            <a class="navbar-brand result-title" href="#">{% trans "Panoramas seeing the point" %} <b>{{ located_point_name }}</b></a>
        {% else %}
            <a class="navbar-brand result-title" href="#">{% trans "Panoramas seeing the searched point" %}</a>
        {% endif %}
    {% endif %}
{% endblock %}

{% block sidebar %}
<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
    {% include "panorama/sidebar-locate-point.html" %}
    </ul>
</div>
{% endblock %}

{% block wrapper-style %}
{% endblock %}

{% block page-wrapper-style %}
style="padding:0px;height:calc(100vh - 50px)"
{% endblock %}

{% block content %}
      <div id="map"></div>
{% endblock content %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "panorama/leaflet/v0.7.7/leaflet.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "panorama/css/leaflet.markercluster/0.4.0/MarkerCluster.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "panorama/css/leaflet.markercluster/0.4.0/MarkerCluster.Default.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "panorama/css/markercluster.override.css" %}" />
{% endblock css %}

{% block js %}
{% localize off %}
<script type='text/javascript' src="{% static "panorama/leaflet/v0.7.7/leaflet.js" %}"></script>
<script type='text/javascript' src="{% static "panorama/js/jquery-3.0.0.min.js" %}"></script>
<script type='text/javascript' src="{% static "panorama/js/leaflet.markercluster/0.4.0/leaflet.markercluster.js" %}"></script>
<script>
    var map;
    var ajaxRequest;
    var plotlist;
    var plotlayers=[];
    // Marker for the point being located
    var locatedIcon = L.icon({
        iconUrl: '{% static "panorama/img/marker-deep-blue.png" %}',
        iconSize: [22, 35],
        iconAnchor: [11, 35],
    });
    // Marker for panorama point
    var panoIcon = L.icon({
        iconUrl: '{% static "panorama/img/marker-red.png" %}',
        iconSize: [22, 35],
        iconAnchor: [11, 35],
        popupAnchor: [0,-50],
    });
    // Markers clusters 
    var markerClusters = L.markerClusterGroup({
    spiderfyOnMaxZoom: false,
    showCoverageOnHover: false,
    maxClusterRadius: 20,
    disableClusteringAtZoom: 19
    });
    var allMarkers = [[{{ located_point_lat }}, {{ located_point_lon }}]];
    // Legend
    var legend = L.control({position: 'bottomright'});

    function accordionMenus() {
        $("ul.side-nav").children().click(function(e) {
            var menu = $(e.target);
            var content = menu.next();
            if (content.is("ul") && content.hasClass("collapse") && !content.hasClass('in')) {
                $(".collapse.in").each(function(){ 
                    $(".collapse.in").animate({height: '1px'}, 500, function(){
                        $(".collapse.in").removeClass("in");
                        $(content).addClass("in");
                    });
                });
            };
        });
    }

    function initmap() {
        // set up the map
        map = new L.Map('map');

        // create the tile layer with correct attribution
        var osmUrl = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
        var osmAttrib = 'Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors';
        var osm = new L.TileLayer(osmUrl, {attribution: osmAttrib, maxZoom: 19});

        // start the map on the point
        map.setView(new L.LatLng({{ located_point_lat }}, {{ located_point_lon }}),13);
        map.addLayer(osm);

        // create the marker for the searched point
        located = new L.marker([{{ located_point_lat }}, {{ located_point_lon }}], {icon: locatedIcon});
        located.addTo(map);

        {% for panorama, distance, bearing, elevation in located_panoramas %}
            var marker = L.marker([{{ panorama.latitude }}, {{ panorama.longitude }}], {icon: panoIcon, riseOnHover: true});
            marker.bindPopup('{{ panorama.name }} ({% trans "at" %} {{ distance|distance }})',{className : 'markerpopup', closeButton: false,}).on('mouseover', marker.openPopup).on('mouseout', marker.closePopup);
            marker.on("click",function(){document.location.href="{% panorama_url panorama bearing elevation %}"});
            markerClusters.addLayer( marker );
            L.polyline([[{{ located_point_lat }}, {{ located_point_lon }}],[{{ panorama.latitude }}, {{ panorama.longitude }}]], {color: '#2636ca', opacity: 0.8, weight: 2, dashArray: "5, 6"}).addTo(map);
            allMarkers.push([{{ panorama.latitude }}, {{ panorama.longitude }}]);
        {% endfor %}

        // Add a legend to the map
        legend.onAdd = function (map) {
            var div = L.DomUtil.create('div', 'legend');
            div.innerHTML += '<div class="legendtitle"><p><i class="fa fa-fw fa-caret-down"></i>{% trans "Legend" %}</p></div>';
            div.innerHTML += '<img src={% static "panorama/img/marker-red.png" %} ><p>{% trans "Panorama" %}</p></br>';
            div.innerHTML += '<img src={% static "panorama/img/marker-deep-blue.png" %} ><p>{% trans "Localized point" %}</p></br>';
            return div;
        };

        map.addLayer( markerClusters );
        map.fitBounds(allMarkers,{padding: [30, 30]});
        legend.addTo(map);

    }
    initmap();
    accordionMenus(); 
</script>
{% endlocalize %}
{% endblock js %}

panorama/templates/panorama/new-refpoint.html
{% extends "panorama/base.html" %}
{% load panorama_url %}

{% block content %}
<form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>
{% endblock content %}

panorama/templates/panorama/new.html
{% extends "panorama/base.html" %}
{% load panorama_url %}
{% load distance_filter %}

{% block content %}
<form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>
{% endblock content %}

panorama/templates/panorama/sidebar-all.html
{% load i18n %}
{% load l10n %}
{% localize off %}
        <li>
            <a href="{% url 'panorama:main' %}"><i class="fa fa-fw fa-home"></i> {% trans "Map" %}</a>
        </li>
{% include "panorama/sidebar-common.html" %}
        <li>
            <a id="locate-gps-btn" href="javascript:;" data-toggle="collapse" data-target="#locate-gps"><i class="fa fa-fw fa-map-marker"></i> {% trans "Locate GPS point" %}<i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="locate-gps" class="sidebarform collapse">
                <li>
                    <form action="{% url 'panorama:locate_custompoint' %}" enctype="multipart/form-data" method="post">{% csrf_token %}
                        {{ custom_point_form.latitude.label_tag }}{{ custom_point_form.latitude }}
                        {{ custom_point_form.longitude.label_tag }}{{ custom_point_form.longitude }}
                        {{ custom_point_form.ground_altitude.label_tag }}{{ custom_point_form.ground_altitude }}
                        {{ custom_point_form.height_above_ground.label_tag }}{{ custom_point_form.height_above_ground }}
                        <input type="submit" class="btn btn-primary btn-sm" value={% trans "Locate" %} />
                    </form>
                </li>
            </ul>
        </li>
        <li>
            <a id="new-refpoint-btn" href="javascript:;" data-toggle="collapse" data-target="#new-refpoint"><i class="fa fa-fw fa-plus-square"></i> {% trans "New reference point" %}<i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="new-refpoint" class="sidebarform collapse">
                <li>
                    <form action="{% url 'panorama:new_refpoint' %}" enctype="multipart/form-data" method="post">{% csrf_token %}
                        {{ newrefpoint_form.name.label_tag }}{{ newrefpoint_form.name }}
                        {{ newrefpoint_form.latitude.label_tag }}{{ newrefpoint_form.latitude }}
                        {{ newrefpoint_form.longitude.label_tag }}{{ newrefpoint_form.longitude }}
                        {{ newrefpoint_form.ground_altitude.label_tag }}{{ newrefpoint_form.ground_altitude }}
                        {{ newrefpoint_form.height_above_ground.label_tag }}{{ newrefpoint_form.height_above_ground }}
                        {{ newrefpoint_form.kind.label_tag }}{{ newrefpoint_form.kind }}
                        <input type="submit" class="btn btn-primary btn-sm" value={% trans "Add" %} />
                    </form>
                </li>
            </ul>
        </li>
        <li>
            <a id="new-pano-btn" href="javascript:;" data-toggle="collapse" data-target="#new-pano"><i class="fa fa-fw fa-plus-square"></i> {% trans "New panorama" %}<i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="new-pano" class="sidebarform collapse">
                <li>
                    <form action="{% url 'panorama:new' %}" enctype="multipart/form-data" method="post">{% csrf_token %}
                        {{ newpanorama_form.name.label_tag }}{{ newpanorama_form.name }}
                        {{ newpanorama_form.image.label_tag }}{{ newpanorama_form.image }}
                        <label for="{{ newpanorama_form.loop.id_for_label }}">{{ newpanorama_form.loop }} {{ newpanorama_form.loop.label }}</label>
                        {{ newpanorama_form.latitude.label_tag }}{{ newpanorama_form.latitude }}
                        {{ newpanorama_form.longitude.label_tag }}{{ newpanorama_form.longitude }}
                        {{ newpanorama_form.ground_altitude.label_tag }}{{ newpanorama_form.ground_altitude }}
                        {{ newpanorama_form.height_above_ground.label_tag }}{{ newpanorama_form.height_above_ground }}
                        <input type="submit" class="btn btn-primary btn-sm" value={% trans "Add" %} />
                    </form>
                </li>
            </ul>
        </li>
{% endlocalize %}

panorama/templates/panorama/sidebar-common.html
{% load i18n %}
{% load static %}
        <li>
            <a id="pano-list-btn" href="javascript:;" data-toggle="collapse" data-target="#panos"><i class="fa fa-fw fa-image"></i> {% trans "Panoramas" %}<i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="panos" class="collapse">
              <div class="panosmore" >
                  <svg>
                      <foreignobject x="0" y="0" width="200" height="30">
                       <p class="panomoretext">&#xf06e;</p>
                      </foreignobject>
                      <!--
                      <polygon points="8 10,0 0,16 0" stroke="#ae3a3a" fill="#ae3a3a" >
                      -->
                  </svg> 
              </div>
              {% for pano in panoramas %}
              <li><a href="{% url 'panorama:view_pano' pano.id %}"><i class="fa fa-fw fa-eye"></i> {{ pano.name }}</a></li>
              {% endfor %}
            </ul>

        </li>
        <li>
            <a id="locate-existing-btn" href="javascript:;" data-toggle="collapse" data-target="#locate-existing"><i class="fa fa-fw fa-circle-thin"></i> {% trans "Locate existing point" %}<i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="locate-existing" class="collapse">
                <li>
                    <form action="{% url 'panorama:locate_refpoint' %}" enctype="multipart/form-data" method="post">{% csrf_token %}
                      {{ refpoints_form.as_p }}
                      <input type="submit" class="btn btn-primary btn-sm" value={% trans "Locate" %} />
                    </form>
                </li>
            </ul>
        </li>

panorama/templates/panorama/sidebar-locate-point.html
{% load i18n %}
{% load l10n %}
{% load panorama_url %}
{% load distance_filter %}
{% include "panorama/sidebar-common.html" %}
{% localize off %}
        <li>
            {% if located_point_name != None %}
                <a href="javascript:;" data-toggle="collapse" data-target="#result"><i class="fa fa-fw fa-eye"></i> {% trans "Results for the point" %} <b>{{ located_point_name }}</b></a>
            {% else %}
                <a href="javascript:;" data-toggle="collapse" data-target="#result"><i class="fa fa-fw fa-eye"></i> {% trans "Results for the searched point" %}</a>
            {% endif %}
            <ul id="result" class="collapse in">
              {% for panorama, distance, bearing, elevation in located_panoramas %}
              <li><a href="{% panorama_url panorama bearing elevation %}" class="pano-result-list"><i class="fa fa-fw fa-map-marker"></i> {{ panorama.name }}<p>({% trans "at" %} {{ distance|distance }})</p></a></li>
              {% endfor %}
            </ul>
        </li>
{% endlocalize %}